default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: app_ai_development

test:
  <<: *default
  database: app_ai_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
